/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_kiwiyou_jda_UdpLoopLibrary */

#ifndef _Included_dev_kiwiyou_jda_UdpLoopLibrary
#define _Included_dev_kiwiyou_jda_UdpLoopLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_kiwiyou_jda_UdpLoopLibrary
 * Method:    queuePacket
 * Signature: (JLjava/nio/ByteBuffer;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_kiwiyou_jda_UdpLoopLibrary_queuePacket
  (JNIEnv *, jclass, jlong, jobject, jstring, jint);

/*
 * Class:     dev_kiwiyou_jda_UdpLoopLibrary
 * Method:    isEmpty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_kiwiyou_jda_UdpLoopLibrary_isEmpty
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_kiwiyou_jda_UdpLoopLibrary
 * Method:    disposeSender
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_kiwiyou_jda_UdpLoopLibrary_disposeSender
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_kiwiyou_jda_UdpLoopLibrary
 * Method:    createLoop
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_dev_kiwiyou_jda_UdpLoopLibrary_createLoop
  (JNIEnv *, jclass, jint);

/*
 * Class:     dev_kiwiyou_jda_UdpLoopLibrary
 * Method:    runLoop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_kiwiyou_jda_UdpLoopLibrary_runLoop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_kiwiyou_jda_UdpLoopLibrary
 * Method:    createStopper
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_kiwiyou_jda_UdpLoopLibrary_createStopper
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_kiwiyou_jda_UdpLoopLibrary
 * Method:    signalStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_kiwiyou_jda_UdpLoopLibrary_signalStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_kiwiyou_jda_UdpLoopLibrary
 * Method:    getSender
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_kiwiyou_jda_UdpLoopLibrary_getSender
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_kiwiyou_jda_UdpLoopLibrary
 * Method:    cloneSender
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_kiwiyou_jda_UdpLoopLibrary_cloneSender
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_kiwiyou_jda_UdpLoopLibrary
 * Method:    initDebugLogger
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_kiwiyou_jda_UdpLoopLibrary_initDebugLogger
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
